---
title: "Selection"
output:
  html_document:
    toc: yes
    toc_depth: 3
#  pdf_document:
#    toc: yes
#    toc_depth: '3'
---

# Selection

## Key Concepts

For a life table based on an insured population, one must consider for
each individual both (i) the age of policy issue and (ii) the time that
has elapsed since policy issue. This is because the insurer typically
underwrites individuals that purchase a policy. Through the
underwriting, the insurer learns additional information about the
individual’s survival distribution that the insurer would not know for a
life randomly drawn from the general population. This additional
information must be accounted for in the calculation of various
quantities such as survival probabilities for the individual and the
value of the individual’s policy.

-   Consider an individual now aged x + t who purchased a policy at
    age x. We say that the individual was **selected**, or **select**,
    at age x (and time $t$ = 0).

-   The additional information gained from underwriting the above
    individual, obtained by surveys and/or a medical examination, is
    assumed to apply for a certain number of years after policy issue
    called the **select period**.

-   Say the select period is $d$ years. For $t$ $<$ $d$, one accounts
    for the initial selection of the above individual at age x; the
    individual’s current age would be written as \[x\] + t (the select
    brackets \[ \] denote the initial age of selection). For $t$ $\ge$
    $d$, one no longer accounts for the initial selection of the
    individual at age x, and the individual’s age would be written
    simply as x + t (with no select brackets \[ \]).

-   An individual has **select mortality** for ages/times within the
    select period that differs from the mortality of the general
    population. An individual has **ultimate mortality** for ages/times
    beyond the select period where their mortality is assumed to be the
    same as a life from the general population.

-   A life table that accounts for both select and ultimate mortality is
    called a **select-and-ultimate life table**.

-   A life table that ignores selection completely is called an
    **aggregate life table**.

-   The previous formulas for the quantities considered so far, such as
    survival probabilities, are still valid in the event of selection.
    One simply has to use information from the select part of the
    select-and-ultimate life table for ages/times within the select
    period.

-   For example, with a select period of 3 years, ${}_{2}p_{[x]}$ =
    $(p_{[x]})$$(p_{[x] + 1})$ and ${}_{5}p_{[x]}$ = $(p_{[x]})$$(p_{[x]
    + 1)}$$(p_{[x] + 2})$$(p_{x + 3})$$(p_{x + 4})$. The p’s with select
    brackets would come from the select part of the select-and-ultimate
    life table, and the p’s without select brackets would come from the
    ultimate part.

-   An illustrative select-and-ultimate table is the

    **Standard Select and Ultimate Survival Model**. This table is
    provided in Appendix D of Dickson et al. For brevity, I will refer
    to this table as the **Standard Select Survival Model**.

## Exercises

2.1. Mortality follows the select-and-ultimate life table:

$\begin{array}{r|r|r|r|r}
\hline
\mathbf{x} & \mathbf{l_{[x]}} & \mathbf{l_{[x] + 1}} & \mathbf{l_{x + 2}} & \mathbf{x + 2}\\
\hline
30 & 9,906 & 9,904 & 9,901 & 32 \\
31 & 9,902 & 9,900 & 9,897 & 33 \\
32 & 9,898 & 9,896 & 9,892 & 34 \\
33 & 9,894 & 9,891 & 9,887 & 35 \\
34 & 9,889 & 9,886 & 9,882 & 36 \\
\hline
\end{array}$

Calculate: 10,000${}_{1|}q_{[30]}$.

\(A) 1 (B) 2 (C) 3 (D) 4 (E) 5

2.2. Suppose mortality follows the Standard Select Survival Model.

Calculate: ${}_{1|2}q_{[70]+1}$.

\(A) 0.025 (B) 0.027 (C) 0.029 (D) 0.031 (E) 0.033

2.3. Consider the following select-and-ultimate life table:

$\begin{array}{r|r|r|r|r|r}
\hline
\mathbf{x} & \mathbf{q_{[x]}} & \mathbf{q_{[x] + 1}} & \mathbf{q_{[x] + 2}} & \mathbf{q_{x + 3}} & \mathbf{x + 3} \\
\hline
60 & 0.09 & 0.11 & 0.13 & 0.15 & 63 \\
61 & 0.10 & 0.12 & 0.14 & 0.16 & 64 \\
62 & 0.11 & 0.13 & 0.15 & 0.17 & 65 \\
63 & 0.12 & 0.14 & 0.16 & 0.18 & 66 \\
64 & 0.13 & 0.15 & 0.17 & 0.19 & 67 \\
\hline
\end{array}$

Assume that deaths follow the uniform distribution of deaths assumption
between integer ages.

Calculate: ${}_{1.6}q_{[61] + 0.75}$.

\(A) 0.1855 (B) 0.1856 (C) 0.1857 (D) 0.1858 (E) 0.1859

2.4. A select-and-ultimate life table with a select period of 2 years is
based on probabilities that satisfy the following relationship:

$q_{[x - i] + i}$ = $\frac{3}{5 - i} \times q_x$ for $i$ = 0, 1.

You are given that $l_{68}$ = 10,000, $q_{66}$ = 0.026, and $q_{67}$ =
0.028.

Calculate: $l_{[65] + 1}$.

\(A) 10,414 (B) 10,451 (C) 10,479 (D) 10,493 (E) 11,069

2.5. Suppose mortality follows the Standard Select Survival Model.

Calculate: $e_{[60] :\overline{5}|}$.

\(A) 4.928 (B) 4.932 (C) 4.936 (D) 4.940 (E) 4.944

2.6. Consider a select-and-ultimate life table with a 2-year select
period.

You are given:

\(i) $l_{[35]}$ = 1500

\(ii) $l_{36}$ = 1472.31

\(iii) $q_{[35]}$ = 0.0240

\(iv) $q_{[35] + 1}$ = 0.0255

Calculate: $l_{35}({}_{1|}q_{35})$.

\(A) 42 (B) 44 (C) 46 (D) 48 (E) 50

2.7. Quinn is currently age 60. He was selected by the PlzDntDie Life
Insurance Company one year ago. Quinn has mortality that follows a
select-and-ultimate life table with a 2-year select period:

\(i) The ultimate part of the model is such that:

$\mu_x$ = 0.0002$(1.1)^x$ for $x$ $\ge$ 0.

\(ii) The select part of the model is such that:

$\mu_{[x] + s}$ = $(0.8)^{2 - s}\mu_{x + s}$ for $x$ $\ge$ 0, 0 $\le$
$s$ $\le$ 2.

Calculate the probability that Quinn survives to age 61.

\(A) 0.938 (B) 0.944 (C) 0.950 (D) 0.956 (E) 0.962

2.8. You are given:

\(i) Mortality follows the Standard Select Survival Model.

\(ii) Deaths are uniformly distributed over each year of age.

Calculate: $\mathring{e}_{[75] + 1 :\overline{1.3}|}$.

\(A) 1.277 (B) 1.280 (C) 1.283 (D) 1.287 (E) 1.290

2.9. For a select and ultimate life table with a 1-year select period:

\(i) $\mu_{[55] + t}$ = 0.5$\mu_{55 + t}$ for 0 $\le$ $t$ $\le$ 1

\(ii) $e_{55}$ = 18.02

\(iii) $e_{[55]}$ = 18.33

Calculate: $e_{56}$.

\(A) 17.60 (B) 17.65 (C) 17.70 (D) 17.75 (E) 17.80

2.10. Consider a population of lives each age 55 and selected at that
age, where 70% are non-smokers and 30% are smokers.

The force of mortality is:

$\mu_{[55] + t}$ = 0.009$t$(0.4 + 0.1$S$) for $t$ $\ge$ 0,

where $S$ = 0 for a non-smoker and $S$ = 1 for a smoker.

Calculate the probability that a randomly chosen life from the above
population will die before age 75.

\(A) 0.51 (B) 0.52 (C) 0.53 (D) 0.54 (E) 0.55

2.11. For a select-and-ultimate life table with a 2-year select period:

\(i) Ultimate mortality follows the Illustrative Life Table.

\(ii) $q_{[x]}$ = 0.5$q_x$, where $q_x$ is from the Illustrative Life
Table.

\(iii) $q_{[x]+1}$ = 0.25$q_{x + 1}$, where $q_{x + 1}$ is from the
Illustrative Life Table.

Calculate the probability that a select life aged 70 will die after age
75.

\(A) 0.79 (B) 0.81 (C) 0.83 (D) 0.85 (E) 0.87

2.12. Consider the setup in Exercise 2.11. Calculate the 4-year
temporary curtate expectation of life for a select life aged 70.

\(A) 3.79 (B) 3.81 (C) 3.83 (D) 3.85 (E) 3.87

### Answers to Exercises

2.1. C

2.2. B

2.3. C

2.4. D

2.5. E

2.6. C

2.7. B

2.8. C

2.9. B

2.10. D

2.11. D

2.12. A

## Past Exam Questions

-   Exam MLC, Fall 2014: \#20

-   Exam MLC, Spring 2014: \#2

-   Exam MLC, Fall 2013: \#3

-   Exam MLC, Spring 2013: \#19

-   Exam MLC, Fall 2012: \#2

-   Exam MLC, Spring 2012: \#1, 13

-   Exam MLC, Sample Questions: \#66, 73, 136, 168

-   Exam MLC, Spring 2007: \#18
